server:
  port: 10001

spring:
  application:
    name: payment10001
  datasource:
    url: jdbc:mysql://localhost:3306/could-test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.vv.common.entity
